"""add_evidence_graphs

Revision ID: 00328acb33af
Revises: 6c08e88f31be
Create Date: 2026-05-25 12:34:58.524180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00328acb33af'
down_revision: Union[str, None] = '6c08e88f31be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_graphs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('segments_json', sa.JSON(), nullable=False),
    sa.Column('entities_json', sa.JSON(), nullable=False),
    sa.Column('dominant_subject', sa.Text(), nullable=True),
    sa.Column('groq_summary', sa.Text(), nullable=True),
    sa.Column('scene_boundaries_json', sa.JSON(), nullable=False),
    sa.Column('groq_reasoning_used', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('total_segments', sa.Integer(), server_default='0', nullable=False),
    sa.Column('confidence', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidence_graphs')
    # ### end Alembic commands ###
