"""Add fusion metadata to EvidenceGraph

Revision ID: 8205bb657d04
Revises: e330ec026969
Create Date: 2026-05-26 20:54:11.895129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8205bb657d04'
down_revision: Union[str, None] = 'e330ec026969'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidence_graphs', sa.Column('modality_coverage_json', sa.JSON(), server_default='{}', nullable=False))
    op.add_column('evidence_graphs', sa.Column('conflict_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('evidence_graphs', sa.Column('conflict_details_json', sa.JSON(), server_default='{}', nullable=False))
    op.add_column('evidence_graphs', sa.Column('structural_video_type', sa.Text(), server_default='none', nullable=False))
    op.add_column('evidence_graphs', sa.Column('evidence_priority_notes_json', sa.JSON(), server_default='{}', nullable=False))
    op.add_column('evidence_graphs', sa.Column('primary_evidence_modality', sa.Text(), server_default='mixed', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evidence_graphs', 'primary_evidence_modality')
    op.drop_column('evidence_graphs', 'evidence_priority_notes_json')
    op.drop_column('evidence_graphs', 'structural_video_type')
    op.drop_column('evidence_graphs', 'conflict_details_json')
    op.drop_column('evidence_graphs', 'conflict_count')
    op.drop_column('evidence_graphs', 'modality_coverage_json')
    # ### end Alembic commands ###
