"""Add s3_audio_uri to jobs

Revision ID: bdbd4759d8a7
Revises: 0013
Create Date: 2026-05-28 21:38:17.497753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdbd4759d8a7'
down_revision: Union[str, None] = '0013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aligned_segments_embedding_hnsw'), table_name='aligned_segments', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_aligned_segments_text_gin'), table_name='aligned_segments', postgresql_using='gin')
    op.drop_column('final_outputs', 'pipeline_version')
    op.drop_column('final_outputs', 'schema_version')
    op.add_column('jobs', sa.Column('s3_audio_uri', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 's3_audio_uri')
    op.add_column('final_outputs', sa.Column('schema_version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.add_column('final_outputs', sa.Column('pipeline_version', sa.VARCHAR(length=10), server_default=sa.text("'v2'::character varying"), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_aligned_segments_text_gin'), 'aligned_segments', [sa.literal_column("to_tsvector('english'::regconfig, text)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_aligned_segments_embedding_hnsw'), 'aligned_segments', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    # ### end Alembic commands ###
