"""v3_tables

Revision ID: ddb75e991d39
Revises: 8205bb657d04
Create Date: 2026-05-28 12:14:59.691410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddb75e991d39'
down_revision: Union[str, None] = '8205bb657d04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('v3_evidence_graphs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('segments_json', sa.JSON(), nullable=False),
    sa.Column('entities_json', sa.JSON(), nullable=False),
    sa.Column('dominant_subject', sa.Text(), nullable=True),
    sa.Column('groq_summary', sa.Text(), nullable=True),
    sa.Column('scene_boundaries_json', sa.JSON(), nullable=False),
    sa.Column('groq_reasoning_used', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('modality_coverage_json', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('conflict_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('conflict_details_json', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('structural_video_type', sa.Text(), server_default='none', nullable=False),
    sa.Column('evidence_priority_notes_json', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('primary_evidence_modality', sa.Text(), server_default='mixed', nullable=False),
    sa.Column('total_segments', sa.Integer(), server_default='0', nullable=False),
    sa.Column('confidence', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_table('v3_extractor_bundles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('asr_segments_json', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('ocr_segments_json', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('audio_segments_json', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('asr_metrics_json', sa.JSON(), nullable=True),
    sa.Column('total_duration_seconds', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_v3_extractor_bundles_job_id', 'v3_extractor_bundles', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_v3_extractor_bundles_job_id', table_name='v3_extractor_bundles')
    op.drop_table('v3_extractor_bundles')
    op.drop_table('v3_evidence_graphs')
    # ### end Alembic commands ###
