"""Add structural fields to SignalManifest

Revision ID: e330ec026969
Revises: 00328acb33af
Create Date: 2026-05-26 20:49:59.231851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e330ec026969'
down_revision: Union[str, None] = '00328acb33af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aligned_segments_embedding_hnsw'), table_name='aligned_segments', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_aligned_segments_text_gin'), table_name='aligned_segments', postgresql_using='gin')
    op.drop_index(op.f('ix_final_outputs_job_id'), table_name='final_outputs')
    op.create_unique_constraint(None, 'final_outputs', ['job_id'])
    op.add_column('signal_manifests', sa.Column('metadata_prior_confidence', sa.Float(), server_default='0.5', nullable=False))
    op.add_column('signal_manifests', sa.Column('structural_score', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('signal_manifests', sa.Column('list_likelihood', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('signal_manifests', sa.Column('countdown_likelihood', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('signal_manifests', sa.Column('overlay_text_density', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('signal_manifests', sa.Column('ordinal_pattern_score', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('signal_manifests', sa.Column('scene_repeat_score', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('signal_manifests', sa.Column('ocr_required', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('signal_manifests', sa.Column('ocr_expected_coverage', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('signal_manifests', sa.Column('asr_expected_value', sa.Float(), server_default='0.5', nullable=False))
    op.add_column('signal_manifests', sa.Column('structural_video_type', sa.String(length=30), server_default='none', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signal_manifests', 'structural_video_type')
    op.drop_column('signal_manifests', 'asr_expected_value')
    op.drop_column('signal_manifests', 'ocr_expected_coverage')
    op.drop_column('signal_manifests', 'ocr_required')
    op.drop_column('signal_manifests', 'scene_repeat_score')
    op.drop_column('signal_manifests', 'ordinal_pattern_score')
    op.drop_column('signal_manifests', 'overlay_text_density')
    op.drop_column('signal_manifests', 'countdown_likelihood')
    op.drop_column('signal_manifests', 'list_likelihood')
    op.drop_column('signal_manifests', 'structural_score')
    op.drop_column('signal_manifests', 'metadata_prior_confidence')
    op.drop_constraint(None, 'final_outputs', type_='unique')
    op.create_index(op.f('ix_final_outputs_job_id'), 'final_outputs', ['job_id'], unique=True)
    op.create_index(op.f('ix_aligned_segments_text_gin'), 'aligned_segments', [sa.literal_column("to_tsvector('english'::regconfig, text)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_aligned_segments_embedding_hnsw'), 'aligned_segments', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###
